In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy.stats import norm, multivariate_normal

In [7]:
customer_data = pd.read_csv('customer_gmm.csv')
display(customer_data)
customer_data = (np.array(customer_data))[:, 1:]
print(customer_data)
print(customer_data.shape)


Index  Gender  Marital status  Age  Education  Income  Occupation  \
0         0       0               0   67          2  124670           1   
1         1       1               1   22          1  150773           1   
2         2       0               0   49          1   89210           0   
3         3       0               0   45          1  171565           1   
4         4       0               0   53          1  149031           1   
...     ...     ...             ...  ...        ...     ...         ...   
1995   1995       1               0   47          1  123525           0   
1996   1996       1               1   27          1  117744           1   
1997   1997       0               0   31          0   86400           0   
1998   1998       1               1   24          1   97968           0   
1999   1999       0               0   25          0   68416           0   

      Settlement size  
0                   2  
1                   2  
2                   0  
3                   1  
4                   1  
...               ...  
1995                0  
1996                0  
1997                0  
1998                0  
1999                0  

[2000 rows x 8 columns]

[[     0      0     67 ... 124670      1      2]
 [     1      1     22 ... 150773      1      2]
 [     0      0     49 ...  89210      0      0]
 ...
 [     0      0     31 ...  86400      0      0]
 [     1      1     24 ...  97968      0      0]
 [     0      0     25 ...  68416      0      0]]
(2000, 7)


# Implementation of Guassian Mixture Models in Python

In [1]:
class GMM:
    def __init__(self,iterations=100,threshold=0.004):
        self.n_components = None
        self.means_ = None
        self.covariances_ = None
        self.prior_ = None
        self.wij = None
        self.iterations = iterations
        self.threshold = threshold
    
    def initialize_parameters(self,data,number_of_clusters):
        self.n_components = number_of_clusters
        n_samples, n_features = data.shape
        self.wij = np.zeros(np.zeros((n_samples, self.n_components)))
        np.random.seed(42)
        chosen = np.random.choice(n_samples, self.n_components, replace = False)
        self.means_ = data[chosen]
        self.prior_ = np.full(self.n_components, 1 / self.n_components)
        self.covs = np.full((self.n_components, n_features, n_features), np.cov(data,rowvar=False))
        
    def fit(self,data,number_of_clusters):
        self.initialize_parameters(data,number_of_clusters)
        log_likelihood = 0
        self.log_likelihood_trace = []
        for iter in self.range(self.iteration):
            new_log_likelihood = self.expectation_step(X)
            self.maximization_step(data)
            if abs(new_log_likelihood - log_likelihood) <= self.threshold:
                self.converged = True
                break
            log_likelihood = new_log_likelihood
            self.log_likelihood_trace.append(log_likelihood)
        return self

    def get_parameters(self):
        return self.means_,self.covariances_,self.prior_  

    def expectation_step(self,X):
        for component in self.n_components:
            self.wij[:,component] = self.prior_[component]*multivariate_normal(self.means_[component],self.covariances_[component]).pdf(X)
        log_likelihood = np.sum(np.log(np.sum(self.wij, axis = 1)))
        self.wij = self.wij/self.wij.sum(axis = 1, keepdims = 1)
        return log_likelihood
    
    def maximization_step(self,X):
        responsbility_weight_sum = self.wij.sum(axis=0)
        self.prior_ = responsbility_weight_sum/X.shape[0]
        self.means_ = np.dot(self.wij.T,X)/responsbility_weight_sum.reshape(-1,1)
        for iter in range(self.n_components):
            self.covariances_[iter] = np.dot(self.wij[:,iter]*(X - self.means[iter]).T,(X - self.means[iter]))/responsbility_weight_sum[iter]
        return self

IndentationError: expected an indented block (2445406860.py, line 44)